### ISSUE TITLE
after 6    led.fade  command not working

### ISSUE THREAD

**Issue by MarksIT** [jgillick/arduino-LEDFader#12]
Hi, this script is really usefull but have a little problem.

I have a sketch when command with 4 I/O  more than 6 led.fade command (start from 0 fade out and start from 255 fade in) in variuos time fade.

If in the schetck write more than 5 command to fade a led , this not working, Arduino ide 1.6.9 compile all without a errors but when I put HIGH pin can start VOID where I have command led.fade this not make nothing. I try to change a pinport after 5 command without succes, i try to make a another led command ex. LEDFader led = LEDFader(10);  to LEDFader leds = LEDFader(10);  without success...

I'm not an advanced programmer and i don't know how to resolve this problem for make a mod in library code.

Bye

**Comment by jgillick** [comment]
I'm sorry, I'm having trouble understanding your question. What do you mean by `start VOID`? Can you post your code?
