### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by MrMdR** [jgillick/arduino-LEDFader#4]
When uploading the example "Multiple LEDs or RGB" I get the following error:

<addr>sketch_oct28a.ino: In function 'void loop()':</addr>
<addr>sketch_oct28a:32: error: request for member 'fade' in 'led', which is of non-class type 'LEDFader_' </addr>
<addr>sketch_oct28a:36: error: request for member 'fade' in 'led', which is of non-class type 'LEDFader_' </addr>

![capture](https://cloud.githubusercontent.com/assets/9408163/4816213/909860f4-5edd-11e4-96d9-2a51fe2263e5.JPG)

**Comment by supinum** [comment]
Try swapping the period(.) in 
```
led.fade(
```
with a dash and arrow (->)
```
led->fade(
```
