### ISSUE TITLE
help on execute a command after fade down 

### ISSUE THREAD

**Issue by delokaver** [jgillick/arduino-LEDFader#8]
Hi,

First to all thanks for these library,
I am a newbie and need some help here :)
I am using these and combining with timer library and it's works flawlessly.
I use these fader to PWM-ing the PIN which later used to control the voltage 

I have a question in regards to read the value ()
my setup is 
- at first sequence :
  led is fade up  (0-255, with 10 second fade_time and keep it ON (255)) along with digitalWrite (HIGH) to turn on the relay (different pin) until the countdown timer pass to it's set time, 
  and that's works nicely.
- and the second sequence :
  since the led is still HIGH (225), I am fading down to 0 along with digitalWrite (LOW) to turn off the relay
  and these also works (but not what I mean to)

my archive is, I need to read the led value so the relay will state LOW (off) if only the led is completely off (0 value) because at a moment I got the relay off (LOW) at set time TOGETHER with led is STARTING to fade down (so I am loosing 10 second reflecting to the fade_time)

I am tried to use bellow code to implement (these was from your example code)

```
 led.fade(0, FADE_TIME);           // fade off led for 10 second
 if (led.is_fading()== false) {        // LED no longer fading
 if (led.get_value() == 255 ) {      // get led value ??? -- 
 digitalWrite(relay, LOW);           // turn off relay after led is completely off (0 value)
 }}
```

I am was try to change the led.get_value to 0 and also changing the led.is_fading to true 
but it doesn't work.

Do I make something wrong here ?

greatly appreciate with your help

**Comment by jgillick** [comment]
Sorry for the delay. Are you still trying to figure this out? Can you post your full code?
